# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Get Job ID from GH API
     id: get-job-id
     env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     run: |
      jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
      job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
      echo "job_id=$job_id" >> $GITHUB_OUTPUT

   - name: Display Job ID
     run: |
      echo Job ID: ${{ steps.get-job-id.outputs.job_id }}
      echo My full job URL is ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.get-job-id.outputs.job_id }}
   
   - name: Get Current Job Log URL
     uses: Tiryoh/gha-jobid-action@v1
     id: jobs
     with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: "build" # input job.<job-id>
        #job_name: "${{ github.job }}"  # if job.<job-id>.name is not specified, this works too
   - name: Output Current Job Log URL
     run: echo ${{ steps.jobs.outputs.html_url }}
